name: Push, build and test docker image

on: 
    push:
        branches: [ "master" ]
           

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Rgis1/Rgis1
          file: ./Rgis1/Rgis1/Dockerfile
          push: true
          tags: dmitryershovferi/rgisfi:latest, dmitryershovferi/rgisfi:${{ github.sha }}
      - name: Run unit tests
        run: dotnet test ./TestProject1/TestProject1.csproj
